// !-- Do Not Hand Edit - This File is generated by CMAKE --!

#ifndef CONFIG_H
#define CONFIG_H 1

#define ONREC_DIR   "/home/mice/OnlineReconstruction/miceOnRec/"
#define STOP_SIGNAL "/home/mice/OnlineReconstruction/miceOnRec/build/stop"
#define ROOT_FOUND    TRUE
#define MONITORING_FOUND    TRUE

#endif // CONFIG_H
